metaG_accession: PRJEB4352
metaT_accession: PRJEB6609
metaG_ena_table: input/ENA_tables/PRJEB4352_metaG_wenv_PE-TEST.txt
metaT_ena_table: input/ENA_tables/PRJEB6609_metaT_wenv_PE-TEST.txt
inputDIR: /vortexfs1/omics/alexander/data/TARA
outputDIR: /vortexfs1/omics/alexander/shu/TARA/snakmake-output-test 
scratch:  /vortexfs1/scratch/sarahhu/tara-test
adapters: input/adapters/illumina-adapters.fa
metaG_sample_list: input/SampleList_ForAssembly_metaG_python-TEST.txt
metaT_sample_list: input/SampleList_ForAssembly_metaT_python-TEST.txt 
megahit_other: --continue --k-list 29,39,59,79,99,119 
megahit_cpu: 80
megahit_min_contig: 1000
megahit_mem: .95
restart-times: 0
max-jobs-per-second: 1
max-status-checks-per-second: 10
local-cores: 1
rerun-incomplete: true
keep-going: true
